version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: base-app
    restart: unless-stopped
    ports:
      - '8001:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default:ro
      - ./docker/supervisord/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    command: /bin/bash -c "./permissions.sh && supervisord -c /etc/supervisor/conf.d/supervisord.conf"

  db:
    image: postgres:latest
    container_name: base-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/pgsql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
    driver: local
